### ISSUE TITLE
PA bills scraper rewrite 2025

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1238]
Pennsylvania Legislature has a new website up at https://www.palegis.us/ (not sure if URL is temporary) and notes that the old website will only be up until the end of 2024. That means we need a rewrite of the bills scraper.

Scope of this ticket is to re-write https://github.com/openstates/openstates-scrapers/blob/main/scrapers/pa/bills.py to target the new site. The scraper should output equivalent (or better/more complete) data than the existing bills scraper.

**Comment by braykuka** [comment]
@jessemortenson I will work on it.

**Comment by jessemortenson** [comment]
Hey @braykuka  - our run of this scraper in production has failed with this being the text and error at the end of the logging. Could you please take a look? 

This scraper is hard to debug (as I'm sure you encountered) because of how long it takes to run. But this error looks like it could be parsing error that maybe could be debugged looking at the specific URL and logic in question.

```
11:43:04 INFO scrapelib: GET - 'https://www.palegis.us/legislation/bills/2023/hb2358'
11:43:05 INFO scrapelib: GET - 'https://www.palegis.us/legislation/amendments/amendment-list?searchby=amendment&sessyr=2023&sessind=0&billbody=h&billtype=b&billnum=2358&billpn=3226'
11:43:07 INFO scrapelib: GET - 'https://www.palegis.us/house/roll-calls/summary?sessYr=2023&sessInd=0&rcNum=1342'
11:43:09 INFO openstates: save vote_event 2023-2024 - 2024-07-01 15:59:00-04:00 - FINAL PASSAGE as vote_event_2457536a-91fd-11ef-aa6e-0a58a9feac02.json
11:43:09 INFO openstates: Message ID: e5d56220-27c5-4cd0-b90a-5465fb489586
11:43:10 INFO scrapelib: GET - 'https://www.palegis.us/house/roll-calls/summary?sessYr=2023&sessInd=0&rcNum=1321'
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 600, in main
    report = do_update(args, other, juris)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 389, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 133, in do_scrape
    partial_report = scraper.do_scrape(**scrape_args, session=session)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 236, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/scrapers/pa/bills.py", line 27, in scrape
    yield from self.scrape_session(chamber, session)
  File "/opt/openstates/openstates/scrapers/pa/bills.py", line 37, in scrape_session
    yield from self.parse_bill(chamber, session, special, link)
  File "/opt/openstates/openstates/scrapers/pa/bills.py", line 82, in parse_bill
    yield from self.parse_votes(bill, page)
  File "/opt/openstates/openstates/scrapers/pa/bills.py", line 261, in parse_votes
    yield from self.parse_chamber_votes(bill, doc, url)
  File "/opt/openstates/openstates/scrapers/pa/bills.py", line 280, in parse_chamber_votes
    date = datetime.datetime.strptime(date_str, "%A %b %d, %Y %I:%M %p")
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%A %b %d, %Y %I:%M %p'
```

**Comment by braykuka** [comment]
@jessemortenson I will check it.

**Comment by braykuka** [comment]
@jessemortenson 
Sometimes, when we scrape pages, the scraped page turns out blank. I believe this might be because the website wasn't responsive to scraping requests at that moment. Additionally, the scraped webpage sometimes contains incorrect URLs, like in these images. As a result, we encounter errors in our web scraping. To address this, I've added retry logic for these cases.
![URL issue](https://github.com/user-attachments/assets/efff76dd-a762-45cc-a6bb-c08041aac3de)
![date issue](https://github.com/user-attachments/assets/8d3578ec-8471-4e12-8c94-267c08b948f6)

**Comment by braykuka** [comment]
For the vote url issues, I've updated the wrong url to the correct url manually.
![image](https://github.com/user-attachments/assets/21678c86-0c5c-4c26-b5ce-853ebadceebc)
