### ISSUE TITLE
IN Events: scraper fails on parsing API response

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1260]
IN Events scraper is failing with error:

```
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base] 02:24:17 INFO openstates: save organization House as organization_0b85d79e-a48b-11ef-beba-46139dc67718.json
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base] Traceback (most recent call last):
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     sys.exit(main())
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 601, in main
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     report = do_update(args, other, juris)
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 390, in do_update
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     report["scrape"] = do_scrape(juris, args, scrapers, active_sessions)
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 167, in do_scrape
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     report[scraper_name] = scraper.do_scrape(**scrape_args)
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 236, in do_scrape
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     for obj in self.scrape(**kwargs) or []:
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/opt/openstates/openstates/scrapers/in/events.py", line 24, in scrape
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     session_no = self.apiclient.get_session_no(self.session)
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]   File "/opt/openstates/openstates/scrapers/in/apiclient.py", line 93, in get_session_no
[2024-11-17, 02:24:19 UTC] {pod_manager.py:472} INFO - [base]     session_no_regex = re.search(r"Session\s+(\d+).+", resp["name"])
[2024-11-17, 02:24:21 UTC] {pod_manager.py:490} INFO - [base] KeyError: 'name'
```

**Comment by jessemortenson** [comment]
Should be fixed
