### ISSUE TITLE
MI events: failing on duplicate data in scrape

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#1261]
MI events scraper is failing on this error, apparently it is scraping one or more duplicate objects. Objects returned in the scrape must be unique, or else data import will fail.

```
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base] Traceback (most recent call last):
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     sys.exit(main())
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 601, in main
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     report = do_update(args, other, juris)
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 405, in do_update
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     report["import"] = do_import(juris, args)
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 271, in do_import
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     report.update(event_importer.import_directory(datadir))
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/importers/base.py", line 285, in import_directory
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     return self.import_data(json_stream())
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/importers/base.py", line 325, in import_data
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     obj_id, what = self.import_item(data)
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]   File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/importers/base.py", line 373, in import_item
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base]     raise DuplicateItemError(data, obj, related.get("sources", []))
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base] openstates.exceptions.DuplicateItemError: attempt to import data that would conflict with data already in the import: {'name': 'Health Policy Subcommittee on Behavioral Health', 'all_day': False, 'start_date': '2024-11-14T14:00:00+00:00', 'end_date': '', 'status': 'tentative', 'classification': 'event', 'description': '', 'upstream_id': '', 'location': <EventLocation: Room 519, House Office Building, Lansing, MI>, 'links': [], 'sources': [{'url': '[https://legislature.mi.gov/Committees/Meeting?meetingID=51c4adda616f41cbae02bd6d5209dfa2',](https://legislature.mi.gov/Committees/Meeting?meetingID=51c4adda616f41cbae02bd6d5209dfa2%27,) 'note': ''}], 'extras': {}, 'dedupe_key': 'House#Health Policy Subcommittee on Behavioral Health#Room 519, House Office Building, Lansing, MI#2024-11-14 09:00:00-05:00', 'jurisdiction_id': 'ocd-jurisdiction/country:us/state:mi/government', 'deleted': False} (already imported as Health Policy Subcommittee on Behavioral Health (2024-11-14T14:00:00+00:00))
[2024-11-18, 00:49:45 UTC] {pod_manager.py:472} INFO - [base] obj1 sources: [{'url': '[https://legislature.mi.gov/Committees/Meeting?meetingID=484957deeeea470d9576e39819b506a7',](https://legislature.mi.gov/Committees/Meeting?meetingID=484957deeeea470d9576e39819b506a7%27,) 'note': ''}]
[2024-11-18, 00:49:46 UTC] {pod_manager.py:490} INFO - [base] obj2 sources: []
```

**Comment by jessemortenson** [comment]
Should be fixed
