### ISSUE TITLE
CA Data Scraper has dependency error. 

### ISSUE THREAD

**Issue by rmcarthur** [openstates/issues#146]
**Issue Description:**
When running the docker compose commands according to the California specific instructions found [here](https://docs.openstates.org/en/latest/contributing/state-specific.html) I'm having a ModuleNotFoundError where SQLAlchemy does not appear to be properly installed by poetry before running the container. 

```
(base) ➜  openstates-scrapers git:(master) docker-compose run --rm scrape ca bills --fast
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/bin/os-update", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 311, in main
    juris, module = get_jurisdiction(args.module)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 49, in get_jurisdiction
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/openstates/openstates/scrapers/ca/__init__.py", line 3, in <module>
    from .bills import CABillScraper
  File "/opt/openstates/openstates/scrapers/ca/bills.py", line 9, in <module>
    from sqlalchemy.orm import sessionmaker
ModuleNotFoundError: No module named 'sqlalchemy'
```
I'm not familiar with poetry or dependency lock, but it could possibly be an error when running the container isolated, instead of in conjunction with the other services? Or am I doing something wrong?

**Comment by rmcarthur** [comment]
On second thought, I think this is actually a documentation bug. 
`docker-compose run --rm scrape ca bills --fast` should be `docker-compose run --rm ca-scrape ca bills --fast`. 
Is that right?

**Comment by jamesturk** [comment]
yes that’s right, ca is the exception here
