### ISSUE TITLE
SD Scraper Errors

### ISSUE THREAD

**Issue by showerst** [openstates/issues#258]
I'm seeing the SD bill scraper consistently bomb out. 

```
10:32:49 INFO scrapelib: GET - https://sdlegislature.gov/api/Bills/22048
10:32:50 INFO scrapelib: GET - https://sdlegislature.gov/api/Bills/ActionLog/22048
Traceback (most recent call last):
  File "/home/showerst/.cache/pypoetry/virtualenvs/openstates-scrapers-sYQ4s34R-py3.7/bin/os-update", line 11, in <module>
    sys.exit(main())
  File "/home/showerst/.cache/pypoetry/virtualenvs/openstates-scrapers-sYQ4s34R-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 318, in main
    report = do_update(args, other, juris)
  File "/home/showerst/.cache/pypoetry/virtualenvs/openstates-scrapers-sYQ4s34R-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 205, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers)
  File "/home/showerst/.cache/pypoetry/virtualenvs/openstates-scrapers-sYQ4s34R-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 89, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/home/showerst/.cache/pypoetry/virtualenvs/openstates-scrapers-sYQ4s34R-py3.7/lib/python3.7/site-packages/openstates/scrape/base.py", line 163, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/showerst/work/ocd/openstates-scrapers/scrapers/sd/bills.py", line 44, in scrape
    yield from self.scrape_bill(chamber, session, bill_id, title, api_link)
  File "/home/showerst/work/ocd/openstates-scrapers/scrapers/sd/bills.py", line 127, in scrape_bill
    yield from self.scrape_action(bill, actions_url, chamber)
  File "/home/showerst/work/ocd/openstates-scrapers/scrapers/sd/bills.py", line 235, in scrape_action
    amd = action["Amendment"]["DocumentId"]
TypeError: string indices must be integers
```

Looks like that endpoint is returning something different here. 

@jessemortenson @NewAgeAirbender

**Comment by jessemortenson** [comment]
Thanks for catching. I did make a fix to another couple small errors this week, and will take a look now

**Comment by jessemortenson** [comment]
In this case it looks like SD somehow messed up their own data structure (a string here, where it appears to be a dict elsewhere). I think you can tell it's messed up even in the SD system by looking at the bill page - https://sdlegislature.gov/Session/Bill/22048 - check the 1/20 action "State Affairs motion to amend": the amendment link is `https://mylrc.sdlegislature.gov/api/Documents/undefined.pdf`

**Comment by showerst** [comment]
Heh, happens to the best of us. 

What we'd usually do here is drop in a statement to check if that's an object, and if not just pass with a self.warning explaining the skip.

I'll drop it in on monday if nobody gets to it first.
