### ISSUE TITLE
IL bill scraper returning no objects

### ISSUE THREAD

**Issue by jessemortenson** [openstates/issues#390]
This is the right template to select if you're reporting an issue with bill or vote data from Open States.

**Issue Description:** IL bill scraper not finding any bills. It looks like there are recent bills that Open States is now missing, for example HR 206

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/bin/os-update", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 318, in main
    report = do_update(args, other, juris)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 205, in do_update
    report["scrape"] = do_scrape(juris, args, scrapers)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/cli/update.py", line 89, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/scrape/base.py", line 173, in do_scrape
    "no objects returned from {} scrape".format(self.__class__.__name__)
openstates.exceptions.ScrapeError: no objects returned from IlBillScraper scrape
```

I am taking a look...

**URL where this issue may be seen (API or OpenStates.org):**

https://openstates.org/search/?query=HR+206&state=il

**Source URL of correct data if applicable:**

https://www.ilga.gov/legislation/billstatus.asp?DocNum=00206&GAID=16&GA=102&DocTypeID=HR&LegID=135957&SessionID=110

**Comment by jamesturk** [comment]
fixed with scrapelib update
