### ISSUE TITLE
CA: VoteEvents <= session year 2009 fail to scrape

### ISSUE THREAD

**Issue by AliAbstract** [openstates/issues#432]
**Issue Description:**
I believe this is somehow related to #12 — there is some data that is no longer able to be processed. Specifically, any bill data from California before 2009 and perhaps after 1999 is the dataset I'm trying to load with the California-specific scrape (`poetry run os-update ca bills session=20092010 people`, replace "20092010" with any session before 2009).

```
[...ERROR TEXT...]
File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.7/lib/python3.7/site-packages/openstates/scrape/base.py", line 261, in validate\n'
INFO - b'    self.__class__.__name__, self._id, "\\n\\t" + "\\n\\t".join(errors)\n'
INFO - b'openstates.exceptions.ScrapeValueError: validation of VoteEvent b65f8c3e-be64-11eb-a8d4-96acee298042 failed: \n'
INFO - b"\t'other' is not one of ['passage', 'amendment', 'committee-passage', 'amendment', 'reading-1', 'reading-3', 'veto', 'veto-override']\n"
INFO - b'\n'
INFO - b"Failed validating 'enum' in schema['properties']['motion_classification']['items']:\n"
INFO - b"    {'enum': ['passage',\n"
INFO - b"              'amendment',\n"
INFO - b"              'committee-passage',\n"
INFO - b"              'amendment',\n"
INFO - b"              'reading-1',\n"
INFO - b"              'reading-3',\n"
INFO - b"              'veto',\n"
INFO - b"              'veto-override'],\n"
INFO - b"     'type': 'string'}\n"
INFO - b'\n'
INFO - b"On instance['motion_classification'][0]:\n"
INFO - b"    'other'\n"
```

Essentially, the enum for Vote Classification as defined [in openstates-core.data.common](https://github.com/openstates/openstates-core/blob/19b468d8e46d54407b5b024a29b5ef43e4e7d01d/openstates/data/common.py#L138-L146) does not have an 'other' which is causing these VoteEvents to fail. I'd like to propose that "other" is added, or that the ability for 'other' to be selected as a correct value is removed.

I'm not entirely sure why years before 2009 have been "archived" (I'm still new to this, something to research) but with the knowledge that they are, I think my first proposal, below, is the more-correct option.

Proposal one:
Change [archived bills](https://github.com/openstates/openstates-scrapers/blob/062ac1ce083b3305b9e99e7ae7a77d6bef923fba/scrapers/ca/bills.py#L684-L689) to behave like [non-archived bills](https://github.com/openstates/openstates-scrapers/blob/062ac1ce083b3305b9e99e7ae7a77d6bef923fba/scrapers/ca/bills.py#L566-L571)
```
                    if "Third Reading" in motion or "3rd Reading" in motion:
                        vtype = "passage"
                    elif "Do Pass" in motion:
                        vtype = "passage"
                    else:
                        vtype = "other" # change to [] 
```

Proposal two:
```
VOTE_CLASSIFICATION_CHOICES = (
    ("passage", "Passage in Chamber"),
    ("amendment", "Amendment Passage"),
    ("committee-passage", "Passage in Committee"),
    ("amendment", "Amendment"),
    ("reading-1", "First Reading"),
    ("reading-3", "Third Reading"),
    ("other", "Other"), # add
)
VOTE_CLASSIFICATIONS = _keys(VOTE_CLASSIFICATION_CHOICES)
```

I'll submit a PR for proposal one tied to this issue and look forward to the feedback.

**Comment by jamesturk** [comment]
Hey,

Thanks for taking a look at this. 

First a note: It is very difficult to keep scrapers running for historical bills, CA might be an exception, but generally we don't worry much about that anymore as that'd require maintaining quite a few additional scrapers that we generally don't run.  When we have a choice to make between fixing something for an old session and keeping the current code clear/maintainable we will favor dropping the ability to rescrape old sessions.  I just wanted to say that up front in case there are other similar issues that come up in what you're working on.

That said, fixing this one to just classify these votes as [] makes the most sense here.  The other type is the same as not classifying at all, which is why we went that way.   there are probably/possibly other lurking things like this, and fixes for them would definitely be welcome :)

**Comment by AliAbstract** [comment]
I appreciate the insight, thank you! I'll try not to be too picky around archived bills then, as I agree it's probably not worth the extra effort unless they're similarly easy to this one.

As for this particular issue, I'm running the 2009 scrape again to see if this fix works and then will be submitting a PR.

**Comment by AliAbstract** [comment]
Since I particularly called out 2009 in this issue, I wanted to update this with the new issue I found. This only affects this particular bill (and perhaps a couple others) but I haven't been able to dive into the code to figure out what issue it is in particular. In case it's a side effect of the very small change I made (I don't expect it is, though) and to prevent submitting multiple PRs for the same issue, I'm going to document the issue here and try to fix it before I go forward with my changes.

```
INFO - b"07:01:08 INFO scrapelib: GET - 'http://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=200920100AB1029'\n"
INFO - b'07:01:09 INFO openstates: save vote_event 20092010 - 2010-01-11 00:00:00-08:00 - Do pass as amended and be re-referred to the Committee on Appropriations. as vote_event_a5aee572-c04b-11eb-86b9-f68813dfa6f4.json\n'
 INFO - b'07:01:09 INFO openstates: save bill AB1029 in 20092010 as bill_a4877510-c04b-11eb-86b9-f68813dfa6f4.json\n'
INFO - b"07:01:10 INFO scrapelib: GET - 'http://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=200920100AB103'\n"
INFO - b'07:01:12 INFO openstates: save vote_event 20092010 - 2009-05-18 00:00:00-07:00 - Do pass and be re-referred to the Committee on Appropriations. as vote_event_a6e82f2a-c04b-11eb-86b9-f68813dfa6f4.json\n'
INFO - b'07:01:12 INFO openstates: save bill AB103 in 20092010 as bill_a5b732fe-c04b-11eb-86b9-f68813dfa6f4.json\n'
INFO - b'Traceback (most recent call last):\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/bin/os-update", line 8, in <module>\n'
INFO - b'    sys.exit(main())\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 318, in main\n'
INFO - b'    report = do_update(args, other, juris)\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 205, in do_update\n'
INFO - b'    report["scrape"] = do_scrape(juris, args, scrapers)\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/cli/update.py", line 89, in do_scrape\n'
INFO - b'    report[scraper_name] = scraper.do_scrape(**scrape_args)\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 168, in do_scrape\n'
INFO - b'    self.save_object(obj)\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 151, in save_object\n'
INFO - b'    raise ve\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 148, in save_object\n'
INFO - b'    obj.validate()\n'
INFO - b'  File "/root/.cache/pypoetry/virtualenvs/openstates-scrapers-vRcYrsYN-py3.9/lib/python3.9/site-packages/openstates/scrape/base.py", line 259, in validate\n'
INFO - b'    raise ScrapeValueError(\n'
INFO - b'openstates.exceptions.ScrapeValueError: validation of Bill a5b732fe-c04b-11eb-86b9-f68813dfa6f4 failed: \n'
INFO - b"\t'' is too short\n"
INFO - b'\n'
INFO - b"Failed validating 'minLength' in schema['properties']['actions']['items']['properties']['related_entities']['items']['properties']['name']:\n"
INFO - b"    {'minLength': 1, 'type': 'string'}\n"
INFO - b'\n'
INFO - b"On instance['actions'][3]['related_entities'][1]['name']:\n"
INFO - b"    ''\n"
