### ISSUE TITLE
Model consent calendar votes (SD & PA examples)

### ISSUE THREAD

**Issue by openstates-bot** [openstates/issues#51]
SD has been failing since 2018-01-13

Based on automated runs it appears that SD has not run successfully in 7 days (2018-01-13).

```
  01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Schaefer"}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Lake"}
01:15:54 ERROR pupa: multiple objects returned for Organization pseudo id ~{"name": "Taxation"}: {'ocd-organization/d1eed466-d898-432f-9ccf-44d4ee49cc20', 'ocd-organization/15fc6d4d-9f34-433b-b2b2-f67e60b086d4'}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Rounds"}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Tulson"}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "York"}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Howard"}
01:15:54 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Livermont"}
01:15:54 ERROR pupa: multiple objects returned for Organization pseudo id ~{"name": "Retirement Laws"}: {'ocd-organization/2230a07b-8eaf-4d12-986c-f0eee99b875c', 'ocd-organization/04938857-bcfe-49d7-a01e-cfba8c3a31ad'}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Anderson"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Bartels"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Conzet"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Diedrich"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Hunhoff"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Jamison"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "McPherson"}
01:15:55 ERROR pupa: cannot resolve pseudo id to Person: ~{"name": "Wismer"}
01:15:55 ERROR pupa: multiple objects returned for Organization pseudo id ~{"name": "Local Government"}: {'ocd-organization/f30971fb-005d-44d9-a8b5-286e7b2fc953', 'ocd-organization/38ab4751-122b-4003-b5fe-b77b228575bf'}
no pupa_settings on path, using defaults
sd (scrape, import)
  people: {}
  bills: {}
import jurisdictions...
import organizations...
import people...
import posts...
import memberships...
import bills...
import events...
import vote events...
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 307, in do_handle
    report['import'] = self.do_import(juris, args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 217, in do_import
    report.update(vote_event_importer.import_directory(datadir))
  File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 190, in import_directory
    return self.import_data(json_stream())
  File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 227, in import_data
    obj_id, what = self.import_item(data)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 265, in import_item
    raise DuplicateItemError(data, obj, related.get('sources', []))
pupa.exceptions.DuplicateItemError: attempt to import data that would conflict with data already in the import: {'bill_id': 'ocd-bill/65e3e6f5-09bd-44df-b75b-437290e9b505', 'organization_id': 'ocd-organization/2432bd5a-3c3f-4784-b1f5-c6134171162b', 'start_date': '2018-01-17', 'identifier': '', 'extras': {}, 'result': 'pass', 'legislative_session_id': UUID('10680d24-ea36-4011-925e-cd8e29aa2dca'), 'motion_classification': ['passage'], 'motion_text': 'Do Pass — 2018'} (already imported as Do Pass — 2018 on HB 1035 in South Dakota 2018 Regular Session)
obj1 sources: ['http://www.sdlegislature.gov/Legislative_Session/Bills/RollCall.aspx?Vote=24556&Session=2018']
obj2 sources: ['http://www.sdlegislature.gov/Legislative_Session/Bills/RollCall.aspx?Vote=24556&Session=2018']
```

Visit http://bobsled.openstates.org for more info.

**Comment by jamesturk** [comment]
depends up on #11, maybe duplicate of it altogether

**Comment by jamesturk** [comment]
closing in favor of #11 -- hopefully to be tackled in OS core 6.0
